name: WeebProfile
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch: {}
jobs:
  weeb_profile:
    runs-on: ubuntu-latest
    steps:
      - name: 🦀 LastFM & Github 🦀
        uses: LucasHenriqueDiniz/WeebProfile@main
        with:
          FILENAME: LastFM.svg
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.WEEB_GH_TOKEN }}
          STORAGE_METHOD: gist
          STYLE: default
          SIZE: half

          PLUGIN_LASTFM: true
          PLUGIN_LASTFM_HIDE_HEADER: true
          PLUGIN_LASTFM_USERNAME: Amayacrab
          PLUGIN_LASTFM_SECTIONS: recent_tracks, top_artists_grid, top_albums_grid

          PLUGIN_GITHUB: true
          PLUGIN_GITHUB_HIDE_HEADER: true
          PLUGIN_GITHUB_USERNAME: LucasHenriqueDiniz
          PLUGIN_GITHUB_SECTIONS: favorite_languages
